package com.maxim.ayon.ui.theme

import androidx.compose.ui.graphics.Color

// DarkColorScheme
val PrimaryDark = Color(0xFF0D0D0D)
val OnPrimaryDark = Color(0xFFFFFFFF)
val TertiaryDark = Color(0xFF323232)
val OnSecondaryDark = Color(0xFF0D0D0D)
val SecondaryDark = Color(0xFFFFFFFF)
val OnTertiaryDark = Color(0xFFFFFFFF)
val SurfaceBrightDark = Color(0x1AFFFFFF)
val SurfaceDimDark = Color(0xFF0D0D0D)
val SurfaceDark = Color(0x1AFFFFFF)
val OnSurfContainerDark = Color(0xFF323232)
val OnSurfaceDimDark = Color(0xFF404040)
val OnSurfaceDark = Color(0xFFFFFFFF)
val OnSurfaceBrightDark = Color(0xFF404040)
val SurfContainerLowDark = Color(0xFFFFFFFF)
val SurfContainerLowestDark = Color(0x66FFFFFF)
val SurfContainerHighDark = Color(0xE60D0D0D)
val OnSurfContainerLowDark = Color(0xFF8C8C8C)
val OnSurfContainerHighDark = Color(0xFF404040)
val SurfContainerHighestDark = Color(0xFFFFFFFF)
val OutlineDark = Color(0x1AFFFFFF)
val OutlineVariantDark = Color(0xFF323232)
val BackgroundDark = Color(0xFF0D0D0D)
val ErrorDark = Color(0xFFF13B3B)
val OnErrorDark = Color(0xFF404040)
val SurfContainerDark = Color(0xFFFFFFFF)
val OnBackgroundDark = Color(0xFF191919)
val InverseOnSurfaceDark = Color(0x99FFFFFF)
val OnSurfaceVariantDark = Color(0xFF323232)

// LightColorScheme
val PrimaryLight = Color(0xFFFFFFFF)
val OnPrimaryLight = Color(0xFF404040)
val SurfaceDimLight = Color(0xFFFFFFFF)
val SurfContainerLowLight = Color(0xFF8C8C8C)
val SecondaryLight = Color(0xFF404040)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SurfaceLight = Color(0xFFECEFF2)
val OnSurfaceLight = Color(0xFF404040)
val OnSurfaceVariantLight = Color(0xFFFFFFFF)
val SurfContainerLight = Color(0xFF404040)
val SurfContainerHighLight = Color(0xCCECEFF2)
val SurfContainerHighestLight = Color(0xFF404040)
val SurfContainerLowestLight = Color(0x66D9D9D9)
val OutlineLight = Color(0xFFFFFFFF)
val OutlineVariantLight = Color(0xFFECEFF2)
val TertiaryLight = Color(0xFFECEFF2)
val OnTertiaryLight = Color(0xFF404040)
val SurfaceBrightLight = Color(0x66FFFFFF)
val OnSurfaceBrightLight = Color(0xFF404040)
val BackgroundLight = Color(0xFFECEFF2)
val ErrorLight = Color(0xFFBA2B2B)
val OnErrorLight = Color(0xFF404040)
val OnBackgroundLight = Color(0xFFF5F7F8)
val InverseOnSurfaceLight = Color(0x99404040)